import type { LearningPath, Reto } from '../types'

export const LEARNING_PATHS: LearningPath[] = [
  {
    id: 'digital-creator',
    title: 'Digital Creator',
    subtitle: 'De cero a crear contenido profesional que vende',
    description: 'La ruta para quien quiere dominar el lado creativo del marketing digital: construyes la marca, escribes el copy, creas el contenido y lo posicionas en Google. Sin necesitar saber código.',
    level: 'principiante',
    duration: '6–8 meses',
    tracks: ['branding', 'copy', 'marketing', 'seo'],
    moduleIds: [
      'branding-1', 'branding-2', 'branding-3', 'branding-capstone',
      'copy-1', 'copy-2', 'copy-3', 'copy-4', 'copy-capstone',
      'modulo-1', 'modulo-2', 'modulo-3', 'modulo-4', 'marketing-capstone',
      'seo-1', 'seo-2', 'seo-3', 'seo-capstone',
    ],
    forWho: 'Emprendedores, freelancers creativos, community managers y cualquier persona que quiera vivir de crear contenido digital con propósito estratégico.',
    outcome: 'Al terminar puedes: crear sistemas de identidad visual completos, escribir copy que convierte para web y ads, gestionar campañas de marketing digital y posicionar contenido en Google.',
  },
  {
    id: 'full-stack-builder',
    title: 'Full-Stack Builder',
    subtitle: 'De la idea al producto en producción',
    description: 'La ruta técnica completa: aprendes a construir aplicaciones web modernas, a integrar IA en el workflow de desarrollo y a medir el impacto con analytics. El stack exacto que usa AlphaDev Studios.',
    level: 'principiante',
    duration: '7–9 meses',
    tracks: ['web', 'ia', 'data'],
    moduleIds: [
      'web-1', 'web-2', 'web-3', 'web-4', 'web-capstone',
      'ia-1', 'ia-2', 'ia-3', 'ia-4', 'ia-capstone',
      'data-1', 'data-2', 'data-3', 'data-4', 'data-5', 'data-capstone',
    ],
    forWho: 'Personas sin experiencia en programación que quieren convertirse en developers full-stack. También para developers con experiencia que quieren modernizar su stack e integrar IA.',
    outcome: 'Al terminar puedes: construir y desplegar aplicaciones SaaS con Next.js y Supabase, crear automatizaciones con IA, medir el comportamiento de usuarios con analytics y tomar decisiones basadas en datos.',
  },
  {
    id: 'ux-designer-pro',
    title: 'UX/UI Designer Pro',
    subtitle: 'Diseño de producto con estrategia de marca',
    description: 'La ruta para diseñadores que quieren ir más allá de la interfaz: integras el pensamiento de marca con el diseño de producto y el copy, produciendo experiencias completamente coherentes.',
    level: 'principiante',
    duration: '8–10 meses',
    tracks: ['uiux', 'branding', 'copy'],
    moduleIds: [
      'uiux-1', 'uiux-2', 'uiux-3', 'uiux-4', 'uiux-5',
      'uiux-6', 'uiux-7', 'uiux-8', 'uiux-capstone',
      'branding-1', 'branding-2', 'branding-3', 'branding-capstone',
      'copy-1', 'copy-2', 'copy-capstone',
    ],
    forWho: 'Diseñadores gráficos que quieren entrar al UX digital, estudiantes de diseño, y profesionales de otras áreas con sensibilidad visual que quieren especializarse en product design.',
    outcome: 'Al terminar puedes: diseñar productos digitales completos (research → prototipo → handoff), crear sistemas de identidad visual desde la estrategia y escribir el UX copy de cualquier interfaz.',
  },
  {
    id: 'performance-marketer',
    title: 'Performance Marketer',
    subtitle: 'Marketing que se mide y que escala',
    description: 'La ruta del marketer data-driven: aprendes a crear campañas que funcionan, a escribir copy que convierte, a posicionarte en Google y a medir todo con analytics profesional. Cada decisión respaldada por datos.',
    level: 'intermedio',
    duration: '7–9 meses',
    tracks: ['marketing', 'copy', 'seo', 'data'],
    moduleIds: [
      'modulo-1', 'modulo-2', 'modulo-3', 'modulo-4', 'marketing-capstone',
      'copy-1', 'copy-2', 'copy-3', 'copy-4', 'copy-capstone',
      'seo-1', 'seo-2', 'seo-3', 'seo-4', 'seo-5', 'seo-capstone',
      'data-1', 'data-2', 'data-3', 'data-4', 'data-5', 'data-capstone',
    ],
    forWho: 'Marketing managers, growth hackers, fundadores de negocios digitales y consultores de marketing que quieren sistematizar su trabajo y justificar sus resultados con datos.',
    outcome: 'Al terminar puedes: gestionar campañas de marketing digital end-to-end, escribir copy para todos los formatos, posicionar contenido en Google con estrategia de clusters y reportar resultados con dashboards profesionales.',
  },
  {
    id: 'agency-ready',
    title: 'Agency Ready',
    subtitle: 'Todo el conocimiento para operar una agencia digital',
    description: 'La ruta completa de AlphaDev Studios: todos los tracks en el orden óptimo para alguien que quiere trabajar en o crear una agencia digital completa. Del diseño al código, del copy al analytics.',
    level: 'avanzado',
    duration: '18–24 meses',
    tracks: ['branding', 'uiux', 'copy', 'marketing', 'web', 'seo', 'data', 'ia'],
    moduleIds: [
      'branding-1', 'branding-2', 'branding-3', 'branding-capstone',
      'uiux-1', 'uiux-2', 'uiux-3', 'uiux-4', 'uiux-5',
      'uiux-6', 'uiux-7', 'uiux-8', 'uiux-capstone',
      'copy-1', 'copy-2', 'copy-3', 'copy-4', 'copy-capstone',
      'modulo-1', 'modulo-2', 'modulo-3', 'modulo-4', 'marketing-capstone',
      'web-1', 'web-2', 'web-3', 'web-4', 'web-capstone',
      'seo-1', 'seo-2', 'seo-3', 'seo-4', 'seo-5', 'seo-capstone',
      'data-1', 'data-2', 'data-3', 'data-4', 'data-5', 'data-capstone',
      'ia-1', 'ia-2', 'ia-3', 'ia-4', 'ia-capstone',
    ],
    forWho: 'Personas ambiciosas que quieren una formación digital completa: desde el diseño y el copy hasta el código y los datos. Ideal para fundadores de agencias, directores creativos que quieren habilidades técnicas, o developers que quieren entender el negocio completo.',
    outcome: 'Al terminar tienes el conocimiento para: diseñar productos, crear sistemas de marca, escribir copy, gestionar campañas, desarrollar aplicaciones, posicionar en SEO, medir con analytics e integrar IA. El kit completo de una agencia digital moderna.',
  },
]

// ─── Retos ────────────────────────────────────────────────────────────────────
// Tiempo-boxed challenges where students build something real and the
// community votes on the best submissions.

export const RETOS: Reto[] = [
  {
    id: 'reto-landing-21',
    title: 'Reto: Lanza tu Landing Page en 21 Días',
    tagline: '21 días. Una landing page real. En producción.',
    description: 'Diseña, escribe y despliega una landing page completa para un producto o servicio real. En 21 días, de idea a URL en producción. Aplican todos los conocimientos de web, copy y branding — en un proyecto que queda en tu portafolio y puede conseguirte clientes.',
    tracks: ['web', 'copy', 'branding'],
    duration: '21 días',
    deliverable: 'URL pública en producción con landing page completa: diseño propio, copy optimizado y métricas de analytics configuradas.',
    requirements: [
      'La landing debe estar en producción en una URL real (Vercel, Netlify o dominio propio)',
      'Debe tener: hero con propuesta de valor clara, sección de beneficios, prueba social (aunque sea ficticia bien elaborada), CTA y formulario funcional',
      'El copy debe aplicar al menos 1 framework (AIDA, PAS o BAB) — mencionar cuál en la presentación',
      'Debe tener GA4 configurado con al menos 1 conversión (form submit o click en CTA)',
      'Mobile responsive verificado en 375px de ancho mínimo',
      'Presentar en 5 minutos máximo: el producto, las decisiones de diseño, el copy elegido y las métricas del primer día',
    ],
    howToSubmit: [
      'Publica la URL en el canal #reto-landing de la comunidad el día 21 a las 11:59pm',
      'Incluye: URL + 3 screenshots (mobile + desktop + hero close-up) + párrafo explicando las decisiones más importantes',
      'Comenta y da feedback a mínimo 3 submissions de otros participantes antes del día 23',
      'La votación de la comunidad abre el día 22 y cierra el día 25',
    ],
    prizes: [
      '1er lugar: Feature en el newsletter de AlphaDev Studios + mención en Instagram + 1 sesión de mentoring 1:1 de 60 minutos',
      '2do lugar: Mención en redes sociales + acceso anticipado al siguiente reto',
      '3er lugar: Mención en la comunidad + badge exclusivo de "Landing Launcher"',
      'Participación: Badge "21-Day Builder" para todos los que entreguen en tiempo',
    ],
    status: 'proximo',
  },
  {
    id: 'reto-contenido-30',
    title: 'Reto: 30 Días de Contenido',
    tagline: '30 días. 30 piezas. Un negocio que empieza a existir en redes.',
    description: 'Crea y publica 30 piezas de contenido en 30 días para un negocio real. Puede ser tu agencia, tu proyecto freelance, o el negocio de alguien que te dé permiso. El objetivo: construir presencia orgánica real con constancia y estrategia — no contenido al azar.',
    tracks: ['marketing', 'copy'],
    duration: '30 días',
    deliverable: 'Carpeta o Notion con las 30 piezas creadas (aunque no todas publicadas), el calendario de contenido, métricas de engagement del período y 3 aprendizajes documentados.',
    requirements: [
      'Mínimo 20 de las 30 piezas deben estar publicadas en redes reales (no simuladas)',
      'El contenido debe cubrir al menos 3 formatos distintos (reels, carruseles, posts estáticos, stories, artículos, etc.)',
      'Cada pieza debe tener copy escrito con intención — no solo imágenes con texto genérico',
      'Documentar el proceso: 1 post semanal en la comunidad del reto mostrando qué publicaste, qué funcionó y qué no',
      'Al final: reporte con métricas reales (alcance, engagement, follows ganados) y análisis honesto',
    ],
    howToSubmit: [
      'El día 30: publica el link a tu perfil + link a la carpeta/Notion con todas las piezas + el reporte',
      'Incluye el screenshot de las métricas del período desde la plataforma (Instagram Insights, LinkedIn Analytics, etc.)',
      'La votación premia al contenido más consistente Y de mayor calidad — no solo el de más likes',
    ],
    prizes: [
      '1er lugar: Feature como caso de estudio en el blog de AlphaDev Studios + 1 sesión de mentoring',
      '2do y 3er lugar: Mencion en redes + badge "Content Machine"',
      'Participación: Badge "30-Day Creator" + acceso al banco de templates de contenido de AlphaDev',
    ],
    status: 'proximo',
  },
  {
    id: 'reto-app-15',
    title: 'Reto: App en 15 Días',
    tagline: '15 días para pasar de idea a aplicación en producción.',
    description: 'Construye y despliega una aplicación web funcional en 15 días con Next.js, TypeScript y Supabase. No importa que sea pequeña — importa que esté en producción, funcione bien y tenga un caso de uso real. La velocidad de entrega es parte del reto.',
    tracks: ['web', 'ia'],
    duration: '15 días',
    deliverable: 'URL en producción en Vercel + repositorio público en GitHub + README con descripción, screenshots y video demo de 2 minutos.',
    requirements: [
      'La app debe estar en producción en Vercel con URL pública accesible para cualquiera',
      'Stack requerido: Next.js + TypeScript + Tailwind (Supabase es opcional pero valorado)',
      'Debe tener al menos 2 features funcionales (no solo una landing estática)',
      'TypeScript strict — tsc --noEmit debe pasar sin errores',
      'Repositorio público en GitHub con README profesional',
      'Video demo de 2 minutos mostrando el uso real de la app (no slides, no presentación — demo en vivo)',
    ],
    howToSubmit: [
      'El día 15: publica en #reto-app: URL de producción + GitHub repo + video demo',
      'Los primeros 3 en publicar reciben bonus de "Fast Launcher" en la votación',
      'La comunidad evalúa: funcionalidad, código limpio (revisando el GitHub) y utilidad del caso de uso',
    ],
    prizes: [
      '1er lugar: Feature en el portfolio de proyectos de AlphaDev Studios + mentoring técnico de 90 minutos',
      '2do lugar: Code review personalizado de 60 minutos + badge "App Builder"',
      '3er lugar: Badge + mención en la comunidad',
      'Bonus "Fast Launcher": badge especial para los primeros 3 en publicar el día 15',
    ],
    status: 'proximo',
  },
  {
    id: 'reto-automatiza-21',
    title: 'Reto: Automatiza tu Agencia en 21 Días',
    tagline: 'Un workflow de IA que te devuelve horas cada semana.',
    description: 'Construye un sistema de automatización con IA que resuelva un problema real de tu flujo de trabajo. En 21 días, de proceso manual a workflow que corre solo. Aplica lo aprendido en el track de IA: n8n, LLMs, y agentes.',
    tracks: ['ia'],
    duration: '21 días',
    deliverable: 'Workflow en n8n exportado como JSON + video demo de 3-5 minutos mostrándolo en funcionamiento + análisis de tiempo ahorrado.',
    requirements: [
      'El workflow debe correr de forma autónoma (trigger → acción → output) sin intervención manual',
      'Debe integrar al menos 1 LLM (Claude, GPT o Gemini) con un prompt bien diseñado',
      'Debe resolver un problema real — documentar cuánto tiempo tardaba el proceso manual vs ahora',
      'Demo en vivo en el video: mostrar el trigger real, el workflow corriendo y el output real generado',
      'Incluir el prompt principal usado con el LLM y al menos 3 ejemplos de inputs/outputs reales',
    ],
    howToSubmit: [
      'El día 21: publica en #reto-automatiza: video + JSON del workflow + análisis de impacto',
      'La votación evalúa: utilidad real del workflow, calidad del output del LLM y creatividad del caso de uso',
      'Bonus: si el workflow ya está en producción y tienes métricas de uso real, mencionarlo suma puntos',
    ],
    prizes: [
      '1er lugar: Feature en el blog de AlphaDev como caso de estudio + sesión de mentoring en automatizaciones',
      '2do y 3er lugar: Badge "Automation Architect" + mención en la newsletter',
      'Participación: Badge "21-Day Automator" + acceso a la biblioteca de workflows de la comunidad',
    ],
    status: 'proximo',
  },
  {
    id: 'reto-brand-10',
    title: 'Reto: Brand en 10 Días',
    tagline: '10 días para crear una identidad que se vea de millones.',
    description: 'Diseña el sistema de identidad visual completo para un negocio en 10 días. Logo, paleta, tipografía y 3 aplicaciones. La velocidad es parte del desafío — los mejores diseñadores no solo hacen buen trabajo, lo hacen rápido.',
    tracks: ['branding', 'uiux'],
    duration: '10 días',
    deliverable: 'Archivo de Figma con link público: sistema de logo (4 variantes), paleta documentada, escala tipográfica y 3 aplicaciones de marca.',
    requirements: [
      'Sistema de logo completo: versión primaria, compacta, monocromática y negativa',
      'Paleta documentada: mínimo 1 primario + 2 neutros + 1 acento, con nombre propio y valor hex de cada uno',
      'Escala tipográfica: mínimo 4 niveles (display/H1, H2/H3, body, caption) con familia y peso definidos',
      'Mínimo 3 aplicaciones: pueden ser perfil de Instagram, mockup de tarjeta, post template, packaging, etc.',
      'El Figma debe tener link de "View" público para que cualquiera pueda verlo',
      'Presentar en 3 minutos: el brief del cliente (ficticio está bien), las decisiones de diseño y el resultado',
    ],
    howToSubmit: [
      'El día 10: publica en #reto-brand: link de Figma + párrafo con el brief y las 3 decisiones de diseño más importantes',
      'La votación evalúa: coherencia del sistema, calidad de ejecución y si el resultado comunica lo que el brief pedía',
      'Feedback obligatorio: comenta en mínimo 2 submissions antes de que cierre la votación',
    ],
    prizes: [
      '1er lugar: Feature en Instagram de AlphaDev Studios + sesión de feedback 1:1 de diseño',
      '2do lugar: Mención + badge "Brand Sprinter"',
      '3er lugar: Badge + mención en la comunidad',
      'Participación: Badge "10-Day Brander" para todos los que entreguen en tiempo',
    ],
    status: 'proximo',
  },
]
